<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ga144.Cvm.Assembler</RootNamespace>
    <AssemblyName>gaasm</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ga144.Cvm.Toolchain\Ga144.Cvm.Toolchain.csproj" />
  </ItemGroup>
</Project>
